# Use Node.js official image
FROM node:20

# Set working directory
WORKDIR /app

# Install necessary system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    python3-pip

# Copy package files and install dependencies
COPY package*.json ./

# Install node-pre-gyp before npm install
RUN npm install -g node-pre-gyp

# Install project dependencies
RUN npm install
RUN npm install -g ts-node

# Copy the client files
COPY . .

# Run the client
CMD ["npm", "start"]
